### ISSUE TITLE
Fails to build tests on latest nightly

### ISSUE THREAD

**Issue by Ryman** [dropbox/rust-alloc-no-stdlib#1]
```rust
pub static mut freelist: [&'static mut [u8]; 16] =
    [&mut [], &mut [], &mut [], &mut [], &mut [], &mut [], &mut [],
    &mut [], &mut [], &mut [], &mut [], &mut [], &mut [], &mut [],
    &mut [], &mut []];
```

At one point, the macros used in `tests/lib.rs` expand to the above, which is allowed on stable and beta, but seems to be denied on nightly. You can try it here: https://is.gd/9tUBN8

This *might* be related to https://github.com/rust-lang/rust/pull/33130

**Comment by danielrh** [comment]
Oh no! I have no idea how to work around it. That is sort of a cornerstone of how the code works (!)
Any ideas?

**Comment by danielrh** [comment]
I can't reproduce the problem, however.

**Comment by Ryman** [comment]
I think it's [fixed now](https://github.com/rust-lang/rust/pull/33130#issuecomment-219139067) but I hadn't had a chance to test the fix since it landed in nightly, glad to hear the fix worked!

**Comment by danielrh** [comment]
Thanks so much for reporting this and following through on the fix (!)
