### ISSUE TITLE
Tests contain UB: Use of uninitialized memory

### ISSUE THREAD

**Issue by saethlin** [dropbox/rust-alloc-no-stdlib#12]
These lines both read the contents of a region allocated with `malloc` without initializing it. They can both be detected by running `cargo miri test`.

https://github.com/dropbox/rust-alloc-no-stdlib/blob/48709cf1d6bfd15900e77827d6b4349667dfde20/tests/lib.rs#L395
https://github.com/dropbox/rust-alloc-no-stdlib/blob/48709cf1d6bfd15900e77827d6b4349667dfde20/tests/lib.rs#L421

I suspect these tests happen to pass at the moment because the size of the allocations is large enough that `malloc` doesn't reuse something out of a pool or free list. It also looks to me like there was a lot of copy+paste in these tests, so I really don't know if this is an oversight or if the tests are supposed to guarantee that this crate only returns initialized memory.

**Comment by Ben-Lichtman** [comment]
To elaborate on this. It would appear that the allocators provided in this crate will freely give out references to uninitialized data which the user is then free to read from / write to.

A concise example of this:
```rs
let mut malloc_global_buffer =
	unsafe { define_allocator_memory_pool!(4096, u8, [0; 200 * 1024 * 1024], malloc) };
let mut ags =
	MallocAllocatedFreelist4096::<u8>::new_allocator(&mut malloc_global_buffer.data, bzero);
let mut uninit = ags.alloc_cell(4);
let boom = uninit[0]; // reading uninitized data from the allocation
```

**Comment by pinkforest** [comment]
@lesniewski and @danielrh - wonder if there is any maintenance going on this crate ? last release was a year ago and this was reported 31 Jan ? Cheers

**Comment by pinkforest** [comment]
I raised re; maintenance status: https://github.com/dropbox/rust-alloc-no-stdlib/issues/16

**Comment by danielrh** [comment]
I didn't see it as a serious problem since it was test code that was calling unsafe then doing something unsafe with it.
I agree returning MaybeUninit is a better idea. Or alternatively we could remove any unsafe usage, since I don't think those are being utilized by upstream crates.
