### ISSUE TITLE
Maintence Status

### ISSUE THREAD

**Issue by pinkforest** [dropbox/rust-alloc-no-stdlib#16]
Hiya whoemever maintains this @danielrh @lesniewski and I think @danielrh owns the crate ?

It seems / I'm guessing that the original maintainers may not be around so pinging people from dropbox gh org:

@cbguder @zacwest @wfraser @euroelessar @zubair-io @joshafeinberg @justinpark 

Is this still being maintained or would it be feasible for us to flag unmaintained or deprecated to any potential users as to signal not to use this ? e.g. would you be happy for people to use this still ?

Just wondering around the issue @saethlin and @Ben-Lichtman raised earlier -

Concerning issue that should be evaluated, acknowledgd and fixed - if any:

https://github.com/dropbox/rust-alloc-no-stdlib/issues/12#issuecomment-1243043738

It would be great if we can point to a patched version - if any here - or flag it as unmaintained if that is feasible -
https://github.com/rustsec/advisory-db/pull/1418

Cheers

**Comment by danielrh** [comment]
There's a bit of difference between unmaintained and "bug in test suite."
I'll push a fix to the test suite soon

**Comment by pinkforest** [comment]
It's a fine line yes and I wanted to clarify this with you / other maintainer(s) first and as such since you are maintaining this crate - So thank you for the clarification that we don't need to flag anything.

We flag unmaintained where the maintainer is completely unreachable due to supply-chain concerns as this could potentially have been - sometimes maintainer(s) let us know that the is no further ongoing maintenance and wishes to let us tell anyone wanting to use it that it is not maintained including any potental security fixes.

To me - personally - passing uninitialised memory via a crate that is intended as an allocator doesn't seem strictly a bug (?)

I mean the issue might have been filed under test suite but to me quickly looking it looks more problematic.
